### ISSUE TITLE
Cannot select screen

### ISSUE THREAD

**Issue by ThisIsSet-L** [darealshinji/superhot-linux-launcher#1]
Select Monitor is greyed out.
```
[westj@Tachikoma SUPERHOT]$ ./launcher.x86_64 
using FLTK version 1.3.4 (http://www.fltk.org)
sh: warning: setlocale: LC_ALL: cannot change locale (ja_JP)
Found path: /home/westj/.local/share/Steam/steamapps/common/SUPERHOT/SUPERHOT.x86_64
Mono path[0] = '/home/westj/.local/share/Steam/steamapps/common/SUPERHOT/SUPERHOT_Data/Managed'
Mono path[1] = '/home/westj/.local/share/Steam/steamapps/common/SUPERHOT/SUPERHOT_Data/Mono'
Mono config path = '/home/westj/.local/share/Steam/steamapps/common/SUPERHOT/SUPERHOT_Data/Mono/etc'
displaymanager : xrandr version warning. 1.5
client has 4 screens
displaymanager screen (0)(DVI-I-0): 1920 x 1080
displaymanager screen (1)(HDMI-0): 1920 x 1080
displaymanager screen (2)(DVI-D-0): 1680 x 1050
Using libudev for joystick management


Importing game controller configs
exit code: 0
```

**Comment by darealshinji** [comment]
The screen detection is done with Xlib's `ScreenCount()` function:
https://github.com/darealshinji/superhot-linux-launcher/blob/aa3d0c0be045b48b67b8a4b0bf653bded0841a85/common.cpp#L194

I don't have a second monitor so I was never able to check if it was working as intended.
Can you compile and run this test program (`g++ test.cpp -lX11 && ./a.out`)? For me it always returns 1 (but I have only 1 monitor).
``` C++
#include <X11/Xlib.h>
#include <iostream>

int get_screen_count(void) {
  Display *dp = XOpenDisplay(":0.0");
  int n = ScreenCount(dp);
  XCloseDisplay(dp);
  return n;
}

int main(void) {
  std::cout << get_screen_count() << std::endl;
  return 0;
}
```
Can you also check what it returns if you replace `XOpenDisplay(":0.0")` with `XOpenDisplay(NULL)`?

**Comment by darealshinji** [comment]
I just saw that FLTK has its own function to get the screen number, `Fl::screen_count()`.
May that will work better. I will later see if I can somehow work with something virtual monitors, perhaps in VirtualBox, so I can properly test it.

**Comment by darealshinji** [comment]
I have updated the code. Now it's using Xinerama to get the screen count and falls back to XScreenCount() if that doesn't work. That way it was possible to detect multiple screens in VirtualBox, I hope it works on a real system too.

**Comment by darealshinji** [comment]
I have partially reverted the screen count changes. I figured out that FLTK will automatically use Xinerama, you just have to install `libxinerama-dev` before building it.

PS:
Let me know if you want me to upload a pre-build version of the launcher.
